import {
  siBun,
  siDocker,
  siElastic,
  siElasticsearch,
  siExpress,
  siFigma,
  siFramer,
  siGit,
  siGithubactions,
  siGitlab,
  siGraphql,
  siJest,
  siKubernetes,
  siLangchain,
  siLinux,
  siMongodb,
  siMysql,
  siNeovim,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siPostgresql,
  siPrisma,
  siPython,
  siReact,
  siRedis,
  siRedux,
  siSass,
  siStorybook,
  siSupabase,
  siTailwindcss,
  siTanstack,
  siTerraform,
  siTurborepo,
  siTypeorm,
  siTypescript,
  siVite,
  siVuedotjs,
  siZod,
} from "simple-icons";

/**
 * Maps skill names (as they appear in messages/*.json stack.categories) to
 * their simple-icons brand glyph. Entries without a reliable brand mark in
 * the catalog (protocols like REST/gRPC, trademark-pulled brands like AWS
 * and Playwright, small libraries like Zustand, or AI concepts like RAG)
 * are left out and fall back to the generic terminal glyph.
 */
const TECH_ICON_PATHS: Record<string, string> = {
  React: siReact.path,
  TypeScript: siTypescript.path,
  "Next.js": siNextdotjs.path,
  "Tailwind CSS": siTailwindcss.path,
  "Framer Motion": siFramer.path,
  Redux: siRedux.path,
  "TanStack Query": siTanstack.path,
  Vite: siVite.path,
  Storybook: siStorybook.path,
  Vue: siVuedotjs.path,
  Sass: siSass.path,
  "Node.js": siNodedotjs.path,
  NestJS: siNestjs.path,
  Express: siExpress.path,
  GraphQL: siGraphql.path,
  Bun: siBun.path,
  Python: siPython.path,
  PostgreSQL: siPostgresql.path,
  MongoDB: siMongodb.path,
  MySQL: siMysql.path,
  Redis: siRedis.path,
  Prisma: siPrisma.path,
  TypeORM: siTypeorm.path,
  Supabase: siSupabase.path,
  Elasticsearch: siElasticsearch.path,
  Docker: siDocker.path,
  Kubernetes: siKubernetes.path,
  "GitLab CI/CD": siGitlab.path,
  "GitHub Actions": siGithubactions.path,
  Terraform: siTerraform.path,
  Nginx: siNginx.path,
  "Elastic APM": siElastic.path,
  LangChain: siLangchain.path,
  Git: siGit.path,
  Neovim: siNeovim.path,
  Figma: siFigma.path,
  Linux: siLinux.path,
  Turborepo: siTurborepo.path,
  Jest: siJest.path,
  Zod: siZod.path,
};

export function getTechIconPath(name: string): string | null {
  return TECH_ICON_PATHS[name] ?? null;
}
